name: demo_01

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: echo 'Hello Amy!'

  deploy:
    runs-on: buuntu-latest

    steps:
      - name: step2
        run: |
          echo 'deploy'
          ls -tlha

          