name: demo_01

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: echo 'Hello Amy!'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: step2
        run: |
          echo 'deploy'
          ls -tlha

  archieve:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: demo
          path: ./
          